title: TypeIt. The Most Versatile jQuery Animated Typing Plugin on the Planet.
email: alex@macarthur.me
description: TypeIt is the most versatile jQuery animated typing plugin on the planet.
version: 4.3.0
baseurl: ""
url: "http://macarthur.me/typeit"
twitter_username: amacarthur89
github_username:  alexmacarthur
opengraph: http://macarthur.me/typeit/assets/img/og-logo.jpg
exclude: [dist, sandbox, README.md, node_modules, gulpfile.js, Gemfile, Gemfile.lock, package.json]
markdown: kramdown
